독립 변수 x가 2개 이상인 경우

# 다중 선형 회귀

In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import optimizers

In [10]:
# 중간 고사, 기말 고사, 가산점 점수
X = np.array([[70, 85, 11], [71, 89, 18], [50, 80, 20], [99, 20, 10], [50, 10, 10]])
y = np.array([73, 82 ,72, 57, 34]) # 최종 성적

model = Sequential()
model.add(Dense(1, input_dim=3, activation='linear'))

sgd = optimizers.SGD(learning_rate=0.0001)
model.compile(optimizer=sgd, loss='mse', metrics=['mse'])
model.fit(X, y, epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 359ms/step - loss: 285.6958 - mse: 285.6958
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 202.9566 - mse: 202.9566
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 148.0806 - mse: 148.0806
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 111.6150 - mse: 111.6150
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 87.3327 - mse: 87.3327
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 71.1230 - mse: 71.1230
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 60.2675 - mse: 60.2675
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 52.9662 - mse: 52.9662
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 48.0260 - mse: 48.0260
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 44.6552 - mse: 44.6552
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 42.3282 - mse: 42.3282
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 40.6957 - mse: 40.6957
Epoch 13/200
1/1

In [11]:
print(model.predict(X))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[77.624245]
 [81.62227 ]
 [67.81482 ]
 [58.02161 ]
 [30.339872]]


In [12]:
X_test = np.array([[20, 99, 10], [40, 50, 20]]) # test data로 예측
print(model.predict(X_test))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[61.368336]
 [48.06384 ]]


# 다중 로지스틱 회귀

정답은 2개중 1개

In [13]:
X = np.array([[0, 0], [0, 1], [1, 0], [0, 2], [1, 1], [2, 0]])
y = np.array([0, 0, 0, 1, 1, 1])

model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['binary_accuracy'])

model.fit(X, y, epochs=200)

Epoch 1/200


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 629ms/step - binary_accuracy: 0.6667 - loss: 0.6486
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - binary_accuracy: 0.6667 - loss: 0.6481
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - binary_accuracy: 0.6667 - loss: 0.6476
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - binary_accuracy: 0.6667 - loss: 0.6471
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - binary_accuracy: 0.6667 - loss: 0.6466
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - binary_accuracy: 0.6667 - loss: 0.6461
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - binary_accuracy: 0.6667 - loss: 0.6456
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - binary_accuracy: 0.6667 - loss: 0.6451
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - binary_accuracy: 0.6667 - loss: 0.6446
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - binary_accuracy: 0.6667 - loss: 0.6442
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - binary_accuracy: 0.6667 - loss: 0.6437
Epoch 12

In [14]:
print(model.predict(X))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[0.42003706]
 [0.49262688]
 [0.7100402 ]
 [0.56552887]
 [0.76650953]
 [0.8922353 ]]
